# =============================================================================
# Grype Ignore Configuration
# =============================================================================
# Документируй причины игнорирования каждой CVE
# =============================================================================

ignore:
  # ---------------------------------------------------------------------------
  # BusyBox CVEs - не применимы для Go приложений
  # ---------------------------------------------------------------------------
  - vulnerability: CVE-2025-60876
    reason: |
      busybox wget HTTP header injection - не применимо.
      Go приложение использует native net/http, не вызывает busybox wget.
      
  - vulnerability: CVE-2025-46394
    reason: |
      busybox tar escape sequences - не применимо.
      Приложение не использует tar для распаковки недоверенных архивов.

  # ---------------------------------------------------------------------------
  # Пример: игнорирование по пакету
  # ---------------------------------------------------------------------------
  # - vulnerability: CVE-XXXX-XXXXX
  #   package:
  #     name: vulnerable-package
  #     version: 1.2.3
  #   reason: "Описание почему игнорируем"

  # ---------------------------------------------------------------------------
  # Пример: игнорирование по fix-state
  # ---------------------------------------------------------------------------
  # - fix-state: not-fixed
  #   reason: "Игнорируем все CVE без доступного фикса"

# =============================================================================
# Fail-on configuration
# =============================================================================
# Останавливать сканирование только на Critical
fail-on-severity: critical

# =============================================================================
# Output configuration  
# =============================================================================
output: "json"
